-- MySQL Script generated by MySQL Workbench
-- Mon Mar 15 00:23:11 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `customerID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone1` INT NOT NULL,
  `phone2` INT NULL DEFAULT NULL,
  `zip` INT NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(2) NOT NULL,
  `address1` VARCHAR(45) NOT NULL,
  `address2` VARCHAR(45) NULL DEFAULT NULL,
  `referred_by` VARCHAR(45) NULL DEFAULT NULL,
  `service` VARCHAR(20) NOT NULL,
  `notes` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`customerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer_invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer_invoice` (
  `invoiceID` INT NOT NULL,
  `customerID` INT NOT NULL,
  `date` DATE NOT NULL,
  `due_now` DECIMAL(9,2) NOT NULL,
  `remitted` DECIMAL(9,2) NOT NULL,
  `total_charge` DECIMAL(9,2) NOT NULL,
  `prior_balance` DECIMAL(9,2) NOT NULL,
  `total_new_charge` DECIMAL(9,2) NOT NULL,
  `taxes` DECIMAL(9,2) NOT NULL,
  `total_credit` DECIMAL(9,2) NOT NULL,
  `total_due` DECIMAL(9,2) NOT NULL,
  PRIMARY KEY (`invoiceID`, `customerID`),
  INDEX `fk_customer_invoice_customer1_idx` (`customerID` ASC) VISIBLE,
  CONSTRAINT `fk_customer_invoice_customer1`
    FOREIGN KEY (`customerID`)
    REFERENCES `mydb`.`customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Services` (
  `serviceID` INT NOT NULL,
  `services_rendered` VARCHAR(512) NOT NULL,
  PRIMARY KEY (`serviceID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`materials` (
  `materialsID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `quantity` INT NOT NULL,
  `price` DECIMAL(9,2) NOT NULL,
  `depreciation` DECIMAL(9,2) NOT NULL,
  PRIMARY KEY (`materialsID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`livestock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`livestock` (
  `livestockID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `quantity` INT NOT NULL,
  `price` DECIMAL(9,2) NOT NULL,
  `height` INT NOT NULL,
  PRIMARY KEY (`livestockID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer_invoice_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer_invoice_item` (
  `invoice_itemID` INT NOT NULL,
  `invoiceID` INT NOT NULL,
  `materialsID` INT NOT NULL,
  `live_stockID` INT NOT NULL,
  `serviceID` INT NOT NULL,
  `charges` DECIMAL(9,2) NOT NULL,
  `credits` DECIMAL(9,2) NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`invoice_itemID`),
  INDEX `fk_InvoiceDetails_CustomerInvoice1_idx` (`invoiceID` ASC) VISIBLE,
  INDEX `fk_InvoiceDetails_LS_Materials1_idx` (`materialsID` ASC) VISIBLE,
  INDEX `fk_InvoiceDetails_LiveStock1_idx` (`live_stockID` ASC) VISIBLE,
  INDEX `serviceID_idx` (`serviceID` ASC) VISIBLE,
  CONSTRAINT `fk_InvoiceDetails_CustomerInvoice1`
    FOREIGN KEY (`invoiceID`)
    REFERENCES `mydb`.`customer_invoice` (`invoiceID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_InvoiceDetails_LS_Materials1`
    FOREIGN KEY (`materialsID`)
    REFERENCES `mydb`.`materials` (`materialsID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_InvoiceDetails_LiveStock1`
    FOREIGN KEY (`live_stockID`)
    REFERENCES `mydb`.`livestock` (`livestockID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `serviceID`
    FOREIGN KEY (`serviceID`)
    REFERENCES `mydb`.`Services` (`serviceID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order_log` (
  `conf_num` INT NOT NULL,
  `date` DATE NOT NULL,
  `supplier` VARCHAR(45) NOT NULL,
  `item` VARCHAR(45) NOT NULL,
  `quantity` INT NOT NULL,
  `ext_price` DECIMAL(9,2) NOT NULL,
  `taxrs` DECIMAL(9,2) NOT NULL,
  `shipping` DECIMAL(9,2) NOT NULL,
  `total` DECIMAL(9,2) NOT NULL,
  PRIMARY KEY (`conf_num`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`livestock_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`livestock_orders` (
  `livestockID` INT NOT NULL,
  `conf_num` INT NOT NULL,
  INDEX `fk_LiveStockOrders_LiveStock1_idx` (`livestockID` ASC) VISIBLE,
  PRIMARY KEY (`conf_num`, `livestockID`),
  CONSTRAINT `fk_LiveStockOrders_LiveStock1`
    FOREIGN KEY (`livestockID`)
    REFERENCES `mydb`.`livestock` (`livestockID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LiveStockOrders_OrderLog1`
    FOREIGN KEY (`conf_num`)
    REFERENCES `mydb`.`order_log` (`conf_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`supplier` (
  `supplierID` INT NOT NULL,
  `preferred` BIT NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address1` VARCHAR(45) NOT NULL,
  `address2` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(32) NOT NULL,
  `zip` INT NOT NULL,
  `order_phone` INT NULL DEFAULT NULL,
  `contact` VARCHAR(45) NULL DEFAULT NULL,
  `contact_phone` INT NULL DEFAULT NULL,
  `terms` VARCHAR(512) NULL DEFAULT NULL,
  `notes` VARCHAR(512) NULL DEFAULT NULL,
  PRIMARY KEY (`supplierID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BOL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BOL` (
  `shipper_num` INT NOT NULL,
  `customerID` INT NOT NULL,
  `conf_num` INT NOT NULL,
  `invoiceID` INT NOT NULL,
  `order_date` DATE NOT NULL,
  `control` VARCHAR(45) NOT NULL,
  `itemID` INT NOT NULL,
  `quantity_ordered` INT NOT NULL,
  `quantity_shipped` INT NOT NULL,
  `quantity_back_ord` INT NOT NULL,
  `eta` DATE NULL DEFAULT NULL,
  `description` VARCHAR(128) NOT NULL,
  `uom` VARCHAR(45) NOT NULL,
  `unit_price` DECIMAL(9,2) NOT NULL,
  `extended_amount` DECIMAL(9,2) NOT NULL,
  `instructions` VARCHAR(1024) NOT NULL,
  `num_items` INT NOT NULL,
  `num_pieces` INT NOT NULL,
  `phone` INT NOT NULL,
  PRIMARY KEY (`shipper_num`),
  INDEX `fk_BOL_OrderLog1_idx` (`conf_num` ASC) VISIBLE,
  INDEX `customerID_idx` (`customerID` ASC) VISIBLE,
  INDEX `invoiceID_idx` (`invoiceID` ASC) VISIBLE,
  CONSTRAINT `fk_BOL_OrderLog1`
    FOREIGN KEY (`conf_num`)
    REFERENCES `mydb`.`order_log` (`conf_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customerID_bol`
    FOREIGN KEY (`customerID`)
    REFERENCES `mydb`.`customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `invoiceID`
    FOREIGN KEY (`invoiceID`)
    REFERENCES `mydb`.`customer_invoice` (`invoiceID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order_supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order_supplier` (
  `conf_num` INT NOT NULL,
  `supplierID` INT NOT NULL,
  INDEX `fk_OrderSupplier_SupplierInfo1_idx` (`supplierID` ASC) VISIBLE,
  PRIMARY KEY (`conf_num`, `supplierID`),
  CONSTRAINT `fk_OrderSupplier_OrderLog1`
    FOREIGN KEY (`conf_num`)
    REFERENCES `mydb`.`order_log` (`conf_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderSupplier_SupplierInfo1`
    FOREIGN KEY (`supplierID`)
    REFERENCES `mydb`.`supplier` (`supplierID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`materials_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`materials_orders` (
  `materialsID` INT NOT NULL,
  `conf_num` INT NOT NULL,
  PRIMARY KEY (`materialsID`, `conf_num`),
  INDEX `fk_materials_has_order_log_order_log1_idx` (`conf_num` ASC) VISIBLE,
  INDEX `fk_materials_has_order_log_materials1_idx` (`materialsID` ASC) VISIBLE,
  CONSTRAINT `fk_materials_has_order_log_materials1`
    FOREIGN KEY (`materialsID`)
    REFERENCES `mydb`.`materials` (`materialsID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materials_has_order_log_order_log1`
    FOREIGN KEY (`conf_num`)
    REFERENCES `mydb`.`order_log` (`conf_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`retail_sales_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`retail_sales_ticket` (
  `ticket_num` INT NOT NULL,
  `customer_customerID` INT NOT NULL,
  `sold_by` VARCHAR(45) NULL,
  `delivery_fee` VARCHAR(45) NULL,
  `sales_tax` DECIMAL(9,2) NULL,
  `total` DECIMAL(9,2) NOT NULL,
  `instructions` VARCHAR(200) NULL,
  PRIMARY KEY (`ticket_num`),
  INDEX `customerID_idx` (`customer_customerID` ASC) VISIBLE,
  CONSTRAINT `fk_customerID_rst`
    FOREIGN KEY (`customer_customerID`)
    REFERENCES `mydb`.`customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item` (
  `itemID` INT NOT NULL,
  `description` VARCHAR(256) NULL,
  `unit_price` DECIMAL(9,2) NULL,
  PRIMARY KEY (`itemID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sales_ticket_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sales_ticket_detail` (
  `ticket_num` INT NOT NULL,
  `itemID` INT NOT NULL,
  `quantity` INT NOT NULL,
  `total_price` DECIMAL(9,2) NOT NULL,
  `sales_ticket_detailcol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ticket_num`),
  INDEX `itemID_idx` (`itemID` ASC) VISIBLE,
  CONSTRAINT `itemID`
    FOREIGN KEY (`itemID`)
    REFERENCES `mydb`.`item` (`itemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ticket_num`
    FOREIGN KEY (`ticket_num`)
    REFERENCES `mydb`.`retail_sales_ticket` (`ticket_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
